## Read the data

This code will give you the data you will use for this PC:

In [1]:
# read web table into pandas DF
import pandas as pd

co2Link='https://docs.google.com/spreadsheets/d/e/2PACX-1vRXjfxeKHQBBCh_oHP-D6RIHEX4eduLjydHb6ZGsU4jo0IK0KKQSoYX_X1FGssC_9hnqCgjKN0K4AVf/pub?gid=775098192&single=true&output=csv'
carbon=pd.read_csv(co2Link)

In [2]:
# here it is:
carbon

,name,metric tonnes of CO2,date_of_information,ranking,region
0,China,1.219600e+10,2023,1,East and Southeast Asia
1,United States,4.795000e+09,2023,2,North America
2,India,2.821000e+09,2023,3,South Asia
3,Russia,1.844000e+09,2023,4,Central Asia
4,Japan,9.602300e+08,2023,5,East and Southeast Asia
...,...,...,...,...,...
211,Falkland Islands (Islas Malvinas),3.600000e+01,2023,212,South America
212,Montserrat,2.400000e+01,2023,213,Central America and the Caribbean
213,Antarctica,1.500000e+01,2023,214,Antarctica
214,"Saint Helena, Ascension, and Tristan da Cunha",1.200000e+01,2023,215,Africa
215,Niue,9.000000e+00,2023,216,Australia and Oceania

As you see, some columns have space, which should be deleted:

In [3]:
# also
carbon.columns

Index(['name', 'metric tonnes of CO2', 'date_of_information', 'ranking',
       'region'],
      dtype='object')

In [39]:
# Like this
carbon.rename(columns={'metric tonnes of CO2':'metric_tonnes_of_CO2'},inplace=True)

# see
carbon.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 216 entries, 0 to 215
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   name                  216 non-null    object
 1   metric_tonnes_of_CO2  216 non-null    float64
 2   date_of_information   216 non-null    int64
 3   ranking               216 non-null    int64
 4   region                216 non-null    object
dtypes: float64(1), int64(2), object(2)
memory usage: 8.6+ KB

You always make a copy:

In [40]:
carbon_copy=carbon.copy()

## Questions

1.Keep all the columns but Ranking

In [41]:
byecolumns=['ranking']
carbon_copy.drop(columns=byecolumns,inplace=True)
carbon_copy

,name,metric_tonnes_of_CO2,date_of_information,region
0,China,1.219600e+10,2023,East and Southeast Asia
1,United States,4.795000e+09,2023,North America
2,India,2.821000e+09,2023,South Asia
3,Russia,1.844000e+09,2023,Central Asia
4,Japan,9.602300e+08,2023,East and Southeast Asia
...,...,...,...,...
211,Falkland Islands (Islas Malvinas),3.600000e+01,2023,South America
212,Montserrat,2.400000e+01,2023,Central America and the Caribbean
213,Antarctica,1.500000e+01,2023,Antarctica
214,"Saint Helena, Ascension, and Tristan da Cunha",1.200000e+01,2023,Africa
215,Niue,9.000000e+00,2023,Australia and Oceania

2.Find the country with minimun CO2 emission in the world

In [42]:
carbon_copy[carbon_copy.metric_tonnes_of_CO2==carbon_copy.metric_tonnes_of_CO2.min()]["name"]

215    Niue
Name: name, dtype: object

3.Find the country with the minium CO2 emission per Region

In [43]:
#con este codigo se asegura que los datos de co2 sean numericos
carbon_copy['metric_tonnes_of_CO2']=pd.to_numeric(carbon_copy['metric_tonnes_of_CO2'],errors='coerce')

In [44]:
#limpia las filas con datos faltantes
carbon_copy_clean=carbon_copy.dropna(subset=['name','region','metric_tonnes_of_CO2'])

In [45]:
#ordenara las emisiones con la region
carbon_copy_sorted=carbon_copy_clean.sort_values(by=['region','metric_tonnes_of_CO2'])

In [46]:
#emite el pais con menor emision de co2 por regiÃ³n
min_emissions=carbon_copy_sorted.groupby('region').first().reset_index()
min_emissions

,region,name,metric_tonnes_of_CO2,date_of_information
0,Africa,"Saint Helena, Ascension, and Tristan da Cunha",12.0,2023
1,Antarctica,Antarctica,15.0,2023
2,Australia and Oceania,Niue,9.0,2023
3,Central America and the Caribbean,Montserrat,24.0,2023
4,Central Asia,Armenia,7144000.0,2023
5,East and Southeast Asia,Timor-Leste,660.0,2023
6,Europe,Faroe Islands,742.0,2023
7,Middle East,Gaza Strip,3913000.0,2023
8,North America,Saint Pierre and Miquelon,57.0,2023
9,South America,Falkland Islands (Islas Malvinas),36.0,2023
10,South Asia,Bhutan,733.0,2023

4.Create a new column by keeping the square root of the the original CO2 column

In [47]:

carbon_copy['metric_tonnes_of_CO2_raiz']=carbon_copy['metric_tonnes_of_CO2']**0.5
CO2_raiz=carbon_copy['metric_tonnes_of_CO2_raiz']
carbon_copy2=carbon_copy.assign(metric_tonnes_of_CO2_raiz=CO2_raiz)

In [48]:
carbon_copy2

,name,metric_tonnes_of_CO2,date_of_information,region,metric_tonnes_of_CO2_raiz
0,China,1.219600e+10,2023,East and Southeast Asia,110435.501538
1,United States,4.795000e+09,2023,North America,69245.938509
2,India,2.821000e+09,2023,South Asia,53113.086900
3,Russia,1.844000e+09,2023,Central Asia,42941.821107
4,Japan,9.602300e+08,2023,East and Southeast Asia,30987.578156
...,...,...,...,...,...
211,Falkland Islands (Islas Malvinas),3.600000e+01,2023,South America,6.000000
212,Montserrat,2.400000e+01,2023,Central America and the Caribbean,4.898979
213,Antarctica,1.500000e+01,2023,Antarctica,3.872983
214,"Saint Helena, Ascension, and Tristan da Cunha",1.200000e+01,2023,Africa,3.464102
215,Niue,9.000000e+00,2023,Australia and Oceania,3.000000

5.Compute the average of CO2. Then, create a new column. This new column is the orginal CO2 minus the average computed

In [49]:

promedio_co2=carbon_copy['metric_tonnes_of_CO2'].mean()
print(promedio_co2)

171564562.3412037

In [50]:

carbon_copy['co2_menos_promedio']=carbon_copy['metric_tonnes_of_CO2']-promedio_co2

In [52]:
#menos_promedio indica el original co2 menos el promedio calculado
menos_promedio=carbon_copy['co2_menos_promedio']
carbon_copy3=carbon_copy.assign(co2_menos_promedio=menos_promedio)
carbon_copy3

,name,metric_tonnes_of_CO2,date_of_information,region,metric_tonnes_of_CO2_raiz,co2_menos_promedio
0,China,1.219600e+10,2023,East and Southeast Asia,110435.501538,1.202444e+10
1,United States,4.795000e+09,2023,North America,69245.938509,4.623435e+09
2,India,2.821000e+09,2023,South Asia,53113.086900,2.649435e+09
3,Russia,1.844000e+09,2023,Central Asia,42941.821107,1.672435e+09
4,Japan,9.602300e+08,2023,East and Southeast Asia,30987.578156,7.886654e+08
...,...,...,...,...,...,...
211,Falkland Islands (Islas Malvinas),3.600000e+01,2023,South America,6.000000,-1.715645e+08
212,Montserrat,2.400000e+01,2023,Central America and the Caribbean,4.898979,-1.715645e+08
213,Antarctica,1.500000e+01,2023,Antarctica,3.872983,-1.715645e+08
214,"Saint Helena, Ascension, and Tristan da Cunha",1.200000e+01,2023,Africa,3.464102,-1.715646e+08
215,Niue,9.000000e+00,2023,Australia and Oceania,3.000000,-1.715646e+08

In [53]:
# carbon_copy.to_csv("carbon_copy.csv",index=False)